name: test-answers
on: workflow_dispatch
jobs:
  test-ans:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get inputs
      env:
        SESSION: ${{secrets.AOC_SESS}}
      shell: bash
      run: |
        echo "Setting up session"
        echo $SESSION > session
        echo "Getting inputs"
        ./getInputs.sh
    - name: setup Python
      shell: bash
      run: ./setupPy.sh
    
    - name: Generate answers
      shell: bash
      run: |
        echo "Generating answers"
        ./genAns.sh

    - name: Test answers
      shell: bash
      run: |
        source venv/bin/activate
        pytest

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.4.2

